### ISSUE TITLE
Docker image for 0.15.4 missing?

### ISSUE THREAD

**Issue by deniszh** [go-graphite/carbonapi#655]
### Discussed in https://github.com/go-graphite/carbonapi/discussions/654

<div type='discussions-op-text'>

<sup>Originally posted by **spoofedpacket** November  9, 2021</sup>
The docker image for 0.15.4 seems to be missing:

https://hub.docker.com/r/gographite/carbonapi/tags

```
$ docker pull gographite/carbonapi:v0.15.4
Error response from daemon: manifest for gographite/carbonapi:v0.15.4 not found: manifest unknown: manifest unknown
```</div>

**Comment by deniszh** [comment]
We should migrate build to Github Actions (and maybe Github Docker repos) because Docker removed autobuilds.

**Comment by akamensky** [comment]
It is still missing, do you need help migrating to Github Actions?

**Comment by deniszh** [comment]
@akamensky : it's done - https://github.com/go-graphite/carbonapi/tree/main/.github/workflows but we had no releases after implementing this. You can't trigger push actions retroactively IIRC. If you know how to do so - let me know. Or we can cut 0.15.5 maybe, @Civil ?

**Comment by deniszh** [comment]
PS: but docker upload [failed](https://github.com/go-graphite/go-carbon/runs/5248184656?check_suite_focus=true) when I implemented that for go-carbon, so, I removed that workflow from it, keep only [ghcr.io](https://github.com/go-graphite/go-carbon/pkgs/container/go-carbon). So, I suspecting same will happen with carbonapi. Docker became really unfriendly to free usage after acquisition, so, probably we should switch to ghcr.io here too.

**Comment by Civil** [comment]
I'd like to ensure that everything in caronapi works and tested on Go 1.18 and after that I'll cut a new release.

**Comment by Civil** [comment]
I put the docker workflow on pause (I completely forgot about it when I was tagging 0.15.5 version to be honest) and I'll remove it completely in near future.

**Comment by akamensky** [comment]
Current release v0.15.6 and image still missing from ghcr.io.

**Comment by Civil** [comment]
I'm hoping to tag 0.16 in near future (once #742 is merged and once I finish changelog, as we are over 200 commits since last release and there were a lot of important changes), I hope 0.16 should get a docker image. Unfortunately I'm not sure it's worth running it for 0.15.6 at this moment.

However if you notice any problems in github workflows, PRs or suggestions/comments are always welcome.

**Comment by Civil** [comment]
Forgot to mention, but docker workflow is defined here:
https://github.com/go-graphite/carbonapi/blob/main/.github/workflows/docker-ghcrio.yml

**Comment by Civil** [comment]
Ok... something is definitely wrong with the conditions for workflow and I have no idea what is that.

I'll try to debug that in separate repos and will try to push a fix in next couple of days.
